[[plugins]]
repo = 'Shougo/dein.vim'


[[plugins]]
repo = 'Shougo/neosnippet.vim'


[[plugins]]
repo = 'Shougo/neosnippet-snippets'


[[plugins]]
repo = 'Shougo/vimshell'
rev = '3787e5'


# enable to show git info
[[plugins]]
repo = 'tpope/vim-fugitive'


# something like fzf (but not using now)
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'


# many colorschemes
[[plugins]]
repo = 'flazz/vim-colorschemes'


# テンプレート中に含まれる特定文字列を置き換える
[[plugins]]
repo = 'thinca/vim-template'
hook_add = 'source ~/.vim/userautoload/plugins/plugin-vim-template.vim'


# Colorize Indent
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = 'source ~/.vim/userautoload/plugins/plugin-vim-indent-guides.vim'


# select and <C--><C--> to commentout/discommentout
[[plugins]]
repo = 'tomtom/tcomment_vim'


# NerdTree
# :NERDTree to call nerdtree
[[plugins]]
repo = 'scrooloose/nerdtree'


# vim-over
# NOTE: Use MacVim.app/Contents/MacOS/Vim or it will not loaded because of erorr
[[plugins]]
repo = 'osyo-manga/vim-over'
hook_add = 'source ~/.vim/userautoload/plugins/plugin-vim-over.vim'


# gist-vim
[[plugins]]
repo = 'mattn/gist-vim'


# multiple-cursors
[[plugins]]
repo = 'terryma/vim-multiple-cursors'


# easy to insert brackets
[[plugins]]
repo = 'tpope/vim-surround'


# very simple vim plugin for easy resizing of your vim windows
[[plugins]]
repo = 'simeji/winresizer'
hook_add = 'let g:winresizer_start_key = "<C-W><C-W>"'


# Auto close parentheses
[[plugins]]
repo = 'cohama/lexima.vim'


# Enable to use python shell in the vim
[[plugins]]
repo = 'klen/python-mode'


# Settings of lightline
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.vim/userautoload/plugins/plugin-lightline.vim'
